# This file was generated by GoReleaser. DO NOT EDIT.
class Codeon < Formula
  desc ""
  homepage "https://github.com/yamajik/codeon"
  version "0.1.13"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/yamajik/codeon/releases/download/0.1.13/codeon_0.1.13_Darwin_x86_64.tar.gz"
    sha256 "dd0bc0b5dddc220349eaa94cd7dd7516c51a7945e8395b7cc968d34727e2e7a1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://github.com/yamajik/codeon/releases/download/0.1.13/codeon_0.1.13_Linux_x86_64.tar.gz"
      sha256 "8db502b7e9897baa17c20d20dd001a92064ba2c941f7bd00a990b5076ce638e3"
    end
  end

  def install
    bin.install "codeon"
  end
end
